import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import type { Album } from "../libs/types";

const Home = ({ albums }: { albums: Album[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Little Photobook</title>
        <meta name="description" content="Generated by anxi0" />
        <link rel="icon" href="/icon.jpeg" />
      </Head>
      <h1>Album List</h1>
      <ul>
        {albums.map((album: Album) => (
          <li
            key={album.id}
            style={{
              margin: "10px",
            }}
          >
            <Link
              href={`/album/${album.id}`}
            >{`${album.id}. ${album.title}`}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/albums");
  const albums: Album[] = await res.json();
  return {
    props: { albums },
  };
};

export default Home;
